config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :home, only: [:index]
  get '/home/get_recipes', to: 'home#get_recipes'

  resources :fridge_ingredients, only: [:index, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/fridge_ingredient.rb
class FridgeIngredient < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :title, :cook_time, :prep_time, :ingredients, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :info, :error, :warning
end

app/controllers/concerns/recipe_getter.rb
class RecipeGetter
  class << self
    def get_recipes
      recipe_ids = []

      Recipe.all.each do |recipe|
        matcher = []

        get_ingredients.each do |ingredient|
          if recipe.ingredients.include?(ingredient)
            matcher << true
          else
            matcher << false
          end
        end

        recipe_ids << recipe.id if matcher.uniq == [true]
      end

      recipe_ids
    end

    def get_ingredients
      FridgeIngredient.pluck(:name)
    end
  end
end

app/controllers/fridge_ingredients_controller.rb
class FridgeIngredientsController < ApplicationController
  before_action :set_ingredients, only: [:index, :create, :destroy]

  def index; end

  def create
    ingredient = FridgeIngredient.new(name: params[:name])

    if ingredient.save
      redirect_to action: "index"

      return
    end

    flash.now[:error] = "Ingredient already exists"

    render :index
  end

  def destroy
    if FridgeIngredient.find(params[:id]).destroy
      flash.now[:error] = "Ingredient deleted!"
    end

    render :index
  end

  private

  def set_ingredients
    @ingredients = FridgeIngredient.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recipies = Recipe.none
  end

  def get_recipes
    recipe_ids = RecipeGetter.get_recipes
    @recipies = Recipe.where(id: recipe_ids)

    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/fridge_ingredients/index.html.slim
h5 My fridge
.row
  .col
    - if @ingredients.present?
      table.table.table-striped
        thead
          tr
            th scope="col"  Name
          tbody
            - @ingredients.each do |ingredient|
              tr
                th scope="row"
                  = ingredient.name
                th scope="row"
                  = link_to fridge_ingredient_path(ingredient), method: :delete, data: { confirm: "Are you sure you want to delete #{ingredient.name}?" }
                    button.btn-close.float-end aria-label="Delete" type="button"
    - else
      = "There is no ingredients"

    = form_tag(fridge_ingredients_path) do
      = text_field_tag 'name', nil, placeholder: 'Add ingredient...'
      = submit_tag "Add"
  .col

app/views/home/index.html.slim
.card.mb-3
  .card-body
    h5.card-title Press the button to get the recipe from ingredients in your fridge
    = link_to home_get_recipes_path, method: :get
      button.btn.btn-primary.btn-lg type="button" GO
.recipies
  - if @recipies.present?
    .row
      - @recipies.each do |recipe|
        .col-lg-4.col-sm-6.mb-4
          .card style=("width: 18rem;")
            img.card-img-top src=recipe.image
            .card-body
              h5.card-title
                = recipe.title
              - eval(recipe.ingredients).each do |ingredient|
                p.card-text
                  = ingredient
  - else
    h5 No recipies found

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Recipeer
    meta content="width=device-width,initial-scale=1" name="viewport" /
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application"
  body
    .container
      nav.navbar.navbar-expand-lg.bg-light
        .container-fluid
          a.navbar-brand href=home_index_path  Recipeer
          button.navbar-toggler aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-bs-target="#navbarSupportedContent" data-bs-toggle="collapse" type="button"
            span.navbar-toggler-icon
          #navbarSupportedContent.collapse.navbar-collapse
            ul.navbar-nav.me-auto.mb-2.mb-lg-0
              li.nav-item
                a.nav-link href=fridge_ingredients_path  My fridge
      - flash.each do |type, msg|
        .alert.alert-danger role="alert"
          = msg

      = yield